# Generated by Django 4.2.30 on 2026-07-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, choices=[('accounting_finance_banking', 'Accounting, Finance & Banking'), ('agriculture_agribusiness', 'Agriculture & Agribusiness'), ('arts_entertainment_media', 'Arts, Entertainment & Media'), ('automotive_aviation_transport', 'Automotive, Aviation & Transportation'), ('construction_engineering_realestate', 'Construction, Engineering & Real Estate'), ('consumer_goods_retail_ecommerce', 'Consumer Goods, Retail & E-commerce'), ('consulting_professional_services', 'Consulting & Professional Services'), ('education_training', 'Education & Training'), ('energy_utilities_mining_oilgas', 'Energy, Utilities, Mining & Oil & Gas'), ('event_hospitality_tourism', 'Event Management, Hospitality & Tourism'), ('fashion_beauty_lifestyle', 'Fashion, Beauty & Lifestyle'), ('food_beverage', 'Food & Beverage'), ('government_public_admin', 'Government & Public Administration'), ('healthcare_medical_pharma', 'Healthcare, Medical & Pharmaceutical'), ('human_resources_recruitment', 'Human Resources & Recruitment'), ('information_technology_telecom', 'Information Technology & Telecommunications'), ('legal_services', 'Legal Services'), ('logistics_supply_chain', 'Logistics, Supply Chain & Warehousing'), ('manufacturing_production', 'Manufacturing & Production'), ('nonprofit_ngo_social', 'Nonprofit, NGO & Social Services'), ('research_science_lab', 'Research, Science & Laboratory Services'), ('sales_marketing_pr', 'Sales, Marketing & Public Relations'), ('security_defense', 'Security & Defense'), ('web_digital_creative', 'Web, Digital Media & Creative Services'), ('other', 'Other')], max_length=60),
        ),
    ]
