# Generated by Django 6.0.5 on 2026-05-25 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(default='Kennedia Consulting', max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(choices=[('banking_finance', 'Banking & Finance'), ('technology', 'Technology'), ('fmcg_retail', 'FMCG / Retail'), ('oil_gas', 'Oil & Gas'), ('healthcare', 'Healthcare'), ('hr_consulting', 'Human Resources / Consulting'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary in Naira', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_display', models.CharField(blank=True, help_text='Optional: e.g. "₦400k – ₦600k" (overrides auto-format)', max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('experience_required', models.CharField(blank=True, choices=[('0-1', '0–1 years (Entry Level)'), ('2-4', '2–4 years'), ('5-8', '5–8 years'), ('9+', '9+ years (Senior)')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('closed', 'Closed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('years_of_experience', models.CharField(blank=True, max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv_file', models.FileField(upload_to='applications/cvs/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes — not visible to applicant')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
