# Generated by Django 4.2.30 on 2026-06-08 07:24

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(upload_to=jobs.models.cv_upload_path),
        ),
    ]
