# Generated by Django 4.2.30 on 2026-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_email',
            field=models.EmailField(blank=True, help_text='Employer contact email — receives notification when someone applies', max_length=254),
        ),
    ]
