# Generated by Django 6.0.5 on 2026-05-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('category', models.CharField(choices=[('career_tips', 'Career Tips'), ('interview_prep', 'Interview Prep'), ('salary_finance', 'Salary & Finance'), ('industry_news', 'Industry News'), ('cv_resume', 'CV & Resume'), ('company_news', 'Company News')], max_length=30)),
                ('author_display', models.CharField(blank=True, help_text='Override author name shown publicly (e.g. "Kennedia Editorial")', max_length=100)),
                ('excerpt', models.TextField(help_text='Short summary shown in listing', max_length=500)),
                ('body', models.TextField(help_text='Full HTML or markdown content')),
                ('emoji', models.CharField(default='📝', max_length=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('read_time', models.CharField(blank=True, help_text='e.g. "5 min"', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
