# Generated by Django 6.0.5 on 2026-05-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='unread', max_length=10)),
                ('admin_reply', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CVWritingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0–2 years)'), ('mid', 'Mid Level (3–6 years)'), ('senior', 'Senior Level (7–12 years)'), ('executive', 'Executive (13+ years)')], max_length=20)),
                ('role_target', models.CharField(blank=True, max_length=200)),
                ('existing_cv', models.FileField(blank=True, null=True, upload_to='cv_requests/')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('read', 'Read'), ('done', 'Done')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV Writing Request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSearchRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_industry', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='job_search_cvs/')),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('read', 'Read'), ('done', 'Done')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Search Registration',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('programme', models.CharField(choices=[('employability', 'Employability Skills (4 weeks)'), ('interview_prep', 'Interview Preparation (2 weeks)'), ('career_strategy', 'Career Strategy & Planning (3 weeks)'), ('personal_branding', 'Personal Branding (2 weeks)'), ('leadership', 'Workplace Leadership (6 weeks)'), ('digital_fluency', 'Digital & Tech Fluency (4 weeks)')], max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('read', 'Read'), ('done', 'Done')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Enrolment',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
