# Generated by Django 6.0.5 on 2026-05-25 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cvwritingrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobsearchregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_search_regs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingenrolment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_enrolments', to=settings.AUTH_USER_MODEL),
        ),
    ]
