# Generated by Django 4.2.30 on 2026-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerJobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('job_title', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('banking_finance', 'Banking & Finance'), ('technology', 'Technology'), ('fmcg_retail', 'FMCG / Retail'), ('oil_gas', 'Oil & Gas'), ('healthcare', 'Healthcare'), ('hr_consulting', 'Human Resources / Consulting'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(default='full_time', max_length=20)),
                ('salary_range', models.CharField(blank=True, help_text='e.g. ₦200k–₦350k/month', max_length=100)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('notification_email', models.EmailField(help_text='Email to receive notifications when candidates apply', max_length=254)),
                ('package', models.CharField(choices=[('free', 'Kennedia Free (₦0)'), ('basic', 'Kennedia Basic (₦50k/month)'), ('standard', 'Kennedia Standard (₦200k/month)'), ('pro', 'Kennedia Pro (₦500k/month)')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('read', 'Read'), ('done', 'Done')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employer Job Request',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
