# Generated by Django 4.2.30 on 2026-06-27 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_job_employer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='savedjob',
            options={},
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='job',
            name='qualification_required',
            field=models.CharField(blank=True, choices=[('secondary', 'Secondary School Certificate or Equivalent'), ('certificate', 'Certificate / Vocational Qualification'), ('diploma', 'Diploma (ND, OND, NCE, HND)'), ('bachelors', "Bachelor's Degree"), ('postgraduate', "Postgraduate Qualification (PGD, Master's, Doctorate)"), ('professional', 'Professional Certification / Fellowship'), ('none', 'No Formal Qualification Required')], max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='requires_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, choices=[('trainee', 'Trainee – 0 years'), ('entry', 'Entry Level – 1–2 years'), ('mid', 'Mid-level – 3–6 years'), ('senior_mid', 'Senior Mid – 7–10 years'), ('senior', 'Senior/Managerial – 12 years+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('accounting_finance_banking', 'Accounting, Finance & Banking'), ('agriculture_agribusiness', 'Agriculture & Agribusiness'), ('arts_entertainment_media', 'Arts, Entertainment & Media'), ('automotive_aviation_transport', 'Automotive, Aviation & Transportation'), ('construction_engineering_realestate', 'Construction, Engineering & Real Estate'), ('consumer_goods_retail_ecommerce', 'Consumer Goods, Retail & E-commerce'), ('consulting_professional_services', 'Consulting & Professional Services'), ('education_training', 'Education & Training'), ('energy_utilities_mining_oilgas', 'Energy, Utilities, Mining & Oil & Gas'), ('event_hospitality_tourism', 'Event Management, Hospitality & Tourism'), ('fashion_beauty_lifestyle', 'Fashion, Beauty & Lifestyle'), ('food_beverage', 'Food & Beverage'), ('government_public_admin', 'Government & Public Administration'), ('healthcare_medical_pharma', 'Healthcare, Medical & Pharmaceutical'), ('human_resources_recruitment', 'Human Resources & Recruitment'), ('information_technology_telecom', 'Information Technology & Telecommunications'), ('legal_services', 'Legal Services'), ('logistics_supply_chain', 'Logistics, Supply Chain & Warehousing'), ('manufacturing_production', 'Manufacturing & Production'), ('nonprofit_ngo_social', 'Nonprofit, NGO & Social Services'), ('research_science_lab', 'Research, Science & Laboratory Services'), ('sales_marketing_pr', 'Sales, Marketing & Public Relations'), ('security_defense', 'Security & Defense'), ('web_digital_creative', 'Web, Digital Media & Creative Services'), ('other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_display',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.cv_upload_path),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'email')},
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='updated_at',
        ),
    ]
